"""create course_day_qa and case_study tables

Revision ID: 0758c652e431
Revises: cf00f2933fe1
Create Date: 2026-08-13 09:49:17.681188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0758c652e431'
down_revision: Union[str, Sequence[str], None] = 'cf00f2933fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_day_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_day_id'], ['course_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_studies_course_day_id'), 'case_studies', ['course_day_id'], unique=False)
    op.create_index(op.f('ix_case_studies_id'), 'case_studies', ['id'], unique=False)
    op.create_table('course_day_qas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_day_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_day_id'], ['course_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_day_qas_course_day_id'), 'course_day_qas', ['course_day_id'], unique=False)
    op.create_index(op.f('ix_course_day_qas_id'), 'course_day_qas', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'TRAINEE'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'TRAINEE'::character varying"))
    op.drop_index(op.f('ix_course_day_qas_id'), table_name='course_day_qas')
    op.drop_index(op.f('ix_course_day_qas_course_day_id'), table_name='course_day_qas')
    op.drop_table('course_day_qas')
    op.drop_index(op.f('ix_case_studies_id'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_course_day_id'), table_name='case_studies')
    op.drop_table('case_studies')
    # ### end Alembic commands ###
