"""add mcq module

Revision ID: b18449fbd1cf
Revises: ee217d274102
Create Date: 2026-07-05 20:14:47.346290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18449fbd1cf'
down_revision: Union[str, Sequence[str], None] = 'ee217d274102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcq_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('pass_percentage', sa.Integer(), nullable=False),
    sa.Column('unlock_after_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('topic_distribution', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcq_assessments_id'), 'mcq_assessments', ['id'], unique=False)
    op.create_table('mcq_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcq_questions_id'), 'mcq_questions', ['id'], unique=False)
    op.create_table('mcq_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('generated_questions', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('remaining_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['mcq_assessments.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcq_attempts_id'), 'mcq_attempts', ['id'], unique=False)
    op.create_table('mcq_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['mcq_assessments.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcq_reports_id'), 'mcq_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcq_reports_id'), table_name='mcq_reports')
    op.drop_table('mcq_reports')
    op.drop_index(op.f('ix_mcq_attempts_id'), table_name='mcq_attempts')
    op.drop_table('mcq_attempts')
    op.drop_index(op.f('ix_mcq_questions_id'), table_name='mcq_questions')
    op.drop_table('mcq_questions')
    op.drop_index(op.f('ix_mcq_assessments_id'), table_name='mcq_assessments')
    op.drop_table('mcq_assessments')
    # ### end Alembic commands ###
