"""create assessment tables

Revision ID: cdb573caf25e
Revises: 0758c652e431
Create Date: 2026-08-13 10:03:40.876075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb573caf25e'
down_revision: Union[str, Sequence[str], None] = '0758c652e431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_day_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assessment_type', sa.Enum('CODING', 'NON_CODING', name='assessmenttype'), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('passing_marks', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_day_id'], ['course_days.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_course_day_id'), 'assessments', ['course_day_id'], unique=False)
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_table('assessment_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submission_path', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('submission_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_submissions_assessment_id'), 'assessment_submissions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_submissions_id'), 'assessment_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_submissions_user_id'), 'assessment_submissions', ['user_id'], unique=False)
    op.add_column('coding_problems', sa.Column('assessment_id', sa.Integer(), nullable=True))
    op.alter_column('coding_problems', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_coding_problems_assessment_id'), 'coding_problems', ['assessment_id'], unique=False)
    op.create_foreign_key(None, 'coding_problems', 'assessments', ['assessment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coding_problems', type_='foreignkey')
    op.drop_index(op.f('ix_coding_problems_assessment_id'), table_name='coding_problems')
    op.alter_column('coding_problems', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('coding_problems', 'assessment_id')
    op.drop_index(op.f('ix_assessment_submissions_user_id'), table_name='assessment_submissions')
    op.drop_index(op.f('ix_assessment_submissions_id'), table_name='assessment_submissions')
    op.drop_index(op.f('ix_assessment_submissions_assessment_id'), table_name='assessment_submissions')
    op.drop_table('assessment_submissions')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_course_day_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
