"""remove course_id from users

Revision ID: ee1062600099
Revises: 05c6f5850311
Create Date: 2026-08-16 20:36:14.936333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1062600099'
down_revision: Union[str, Sequence[str], None] = '05c6f5850311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
